#!/usr/bin/env bash
# =============================================================================
# publish-production.sh
# Generates docker-compose.production.yaml and a ready-to-use .env with random
# PostgreSQL passwords, Watchtower enabled, and no Aspire dashboard or Scalar.
#
# Usage:
#   ./scripts/publish-production.sh [output-dir]
#
# Defaults to writing into the repo root if no output dir is given.
# Requires: .NET SDK, Aspire CLI, openssl
# =============================================================================

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
APPHOST_DIR="$REPO_ROOT/src/Aspire/Nocturne.Aspire.Host"
OUTPUT_DIR="${1:-$REPO_ROOT}"

# Temp dir for aspire publish output (cleaned up on exit)
WORK_DIR="$(mktemp -d)"
trap 'rm -rf "$WORK_DIR"' EXIT

echo "[publish-production] Generating production docker-compose..."

# Run aspire publish with production flags:
#   - Dashboard disabled  (no compose-dashboard container)
#   - Scalar disabled     (no scalar container)
#   - Watchtower enabled  (auto-update containers daily)
export Aspire__OptionalServices__AspireDashboard__Enabled=false
export Aspire__OptionalServices__Scalar__Enabled=false
export Aspire__OptionalServices__Watchtower__Enabled=true

aspire publish \
    --project "$APPHOST_DIR" \
    --publisher docker-compose \
    --output-path "$WORK_DIR" \
    --no-build

if [ ! -f "$WORK_DIR/docker-compose.yaml" ]; then
    echo "[publish-production] ERROR: aspire publish did not produce docker-compose.yaml" >&2
    exit 1
fi

# Move compose to final location
mv "$WORK_DIR/docker-compose.yaml" "$OUTPUT_DIR/docker-compose.production.yaml"
echo "[publish-production] Wrote $OUTPUT_DIR/docker-compose.production.yaml"

# ---------------------------------------------------------------------------
# Generate .env.production with random passwords and sensible defaults
# ---------------------------------------------------------------------------

generate_password() {
    openssl rand -base64 32 | tr -d '/+=' | head -c 32
}

POSTGRES_PASSWORD="$(generate_password)"
POSTGRES_MIGRATOR_PASSWORD="$(generate_password)"
POSTGRES_APP_PASSWORD="$(generate_password)"
POSTGRES_WEB_PASSWORD="$(generate_password)"
INSTANCE_KEY="$(generate_password)"

# Read the aspire-generated .env and fill in production values.
# Any var ending in _PASSWORD= or _IMAGE= with an empty value gets populated.
if [ -f "$WORK_DIR/.env" ]; then
    while IFS= read -r line; do
        case "$line" in
            "NOCTURNE_API_IMAGE="*)
                echo "NOCTURNE_API_IMAGE=ghcr.io/nightscout/nocturne/api:latest" ;;
            "NOCTURNE_WEB_IMAGE="*)
                echo "NOCTURNE_WEB_IMAGE=ghcr.io/nightscout/nocturne/web:latest" ;;
            "NOCTURNE_API_PORT="*)
                echo "NOCTURNE_API_PORT=8080" ;;
            "POSTGRES_USERNAME="*)
                echo "POSTGRES_USERNAME=nocturne" ;;
            "POSTGRES_PASSWORD="*)
                echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" ;;
            "POSTGRES_MIGRATOR_PASSWORD="*)
                echo "POSTGRES_MIGRATOR_PASSWORD=$POSTGRES_MIGRATOR_PASSWORD" ;;
            "POSTGRES_APP_PASSWORD="*)
                echo "POSTGRES_APP_PASSWORD=$POSTGRES_APP_PASSWORD" ;;
            "POSTGRES_WEB_PASSWORD="*)
                echo "POSTGRES_WEB_PASSWORD=$POSTGRES_WEB_PASSWORD" ;;
            "INSTANCE_KEY="*)
                echo "INSTANCE_KEY=$INSTANCE_KEY" ;;
            "NOCTURNE_POSTGRES_SERVER_BINDMOUNT_0="*)
                echo "NOCTURNE_POSTGRES_SERVER_BINDMOUNT_0=./container-init" ;;
            *)
                echo "$line" ;;
        esac
    done < "$WORK_DIR/.env" > "$OUTPUT_DIR/.env.production"
else
    # Fallback: write a minimal .env.production if aspire didn't generate one
    cat > "$OUTPUT_DIR/.env.production" << EOF
# Nocturne Production Environment
# Generated by scripts/publish-production.sh

NOCTURNE_API_IMAGE=ghcr.io/nightscout/nocturne/api:latest
NOCTURNE_WEB_IMAGE=ghcr.io/nightscout/nocturne/web:latest
NOCTURNE_API_PORT=8080

NOCTURNE_POSTGRES_SERVER_BINDMOUNT_0=./container-init
POSTGRES_USERNAME=nocturne
POSTGRES_PASSWORD=$POSTGRES_PASSWORD
POSTGRES_MIGRATOR_PASSWORD=$POSTGRES_MIGRATOR_PASSWORD
POSTGRES_APP_PASSWORD=$POSTGRES_APP_PASSWORD
POSTGRES_WEB_PASSWORD=$POSTGRES_WEB_PASSWORD

INSTANCE_KEY=$INSTANCE_KEY
PUBLIC_BASE_DOMAIN=
EOF
fi

echo "[publish-production] Wrote $OUTPUT_DIR/.env.production"
echo ""
echo "[publish-production] Done! Next steps:"
echo "  1. Copy docs/postgres/container-init/ next to docker-compose.production.yaml"
echo "     (or update NOCTURNE_POSTGRES_SERVER_BINDMOUNT_0 in .env.production)"
echo "  2. Set PUBLIC_BASE_DOMAIN to your domain (e.g. nocturne.example.com)"
echo "  3. Optionally configure Discord/Telegram/Slack/WhatsApp credentials"
echo "  4. Run: docker compose -f docker-compose.production.yaml up -d"
